In [1]:
##Q1. Create an array having consecutive natural numbers of size 6x3 and print it
import numpy as np
arr18num = np.arange(18).reshape(6, 3)
print("arr18num:{}".format(arr18num))

arr18num:[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [2]:
#Q2: Rename all the columns in the dataset as per your wish and save it in another dataframe and name it df2

import pandas as pd
df1 = pd.read_excel("Week 1 Dataset.xlsx")
##print (df1)
df2=df1.rename(columns={"Name":"Initials","Income per month":"Salary", "State":"StateName","Age":"YearsOld","Sex":"Gender","Number of siblings":"Siblings"})
print (df2)

  Initials  Salary      StateName  YearsOld Gender  Siblings
0        A      50     Tamil Nadu        23      M         0
1        B      34      Karnataka        37      F         3
2        C      54     Tamil Nadu        35      F         1
3        D      24  Uttar Pradesh        26      F         4
4        E      19          Bihar        59      M         5
5        F      21          Bihar        48      M         6
6        G      40          Delhi        30      F         2
7        H      20  Uttar Pradesh        72      M        10
8        I      30      Telangana        22      F         0
9        J      18    Chattisgarh        42      M         7


In [3]:
#Q3: After you have created df2, make the same changes in the original dataframe using the inplace
df1.rename(columns={"Name":"Initials","Income per month":"Salary", "State":"StateName","Age":"YearsOld","Sex":"Gender","Number of siblings":"Siblings"},inplace=True)
print(df1)


  Initials  Salary      StateName  YearsOld Gender  Siblings
0        A      50     Tamil Nadu        23      M         0
1        B      34      Karnataka        37      F         3
2        C      54     Tamil Nadu        35      F         1
3        D      24  Uttar Pradesh        26      F         4
4        E      19          Bihar        59      M         5
5        F      21          Bihar        48      M         6
6        G      40          Delhi        30      F         2
7        H      20  Uttar Pradesh        72      M        10
8        I      30      Telangana        22      F         0
9        J      18    Chattisgarh        42      M         7


In [4]:
#Q4: Show only the columns information, sex and number of siblings
SelectedColumns = df1.iloc[:,4:6]
SelectedColumns

Gender  Siblings
0      M         0
1      F         3
2      F         1
3      F         4
4      M         5
5      M         6
6      F         2
7      M        10
8      F         0
9      M         7

In [5]:
#Q5: Use iloc method to print data from column 1 to 4 and rows 3 to 9
SelectedData = df1.iloc[3:10,0:4]
SelectedData

Initials  Salary      StateName  YearsOld
3        D      24  Uttar Pradesh        26
4        E      19          Bihar        59
5        F      21          Bihar        48
6        G      40          Delhi        30
7        H      20  Uttar Pradesh        72
8        I      30      Telangana        22
9        J      18    Chattisgarh        42

In [6]:
#Q6: Find the total value count of number of siblings in the given dataset
df2["Siblings"].value_counts()

0     2
10    1
7     1
6     1
5     1
4     1
3     1
2     1
1     1
Name: Siblings, dtype: int64

In [7]:
#Q7: What are dependant and independent varibles in our dataset? 
#Not very clear but I assume the following
#Independent variables X are Name, Income per month, State_name, Age, Sex and 
#Dependant varialbe Y is Number of siblings
X = df1.iloc[:,:-1].values
y = df1.iloc[:, -1].values
print(X)
print(y)

[['A' 50 'Tamil Nadu' 23 'M']
 ['B' 34 'Karnataka' 37 'F']
 ['C' 54 'Tamil Nadu' 35 'F']
 ['D' 24 'Uttar Pradesh' 26 'F']
 ['E' 19 'Bihar' 59 'M']
 ['F' 21 'Bihar' 48 'M']
 ['G' 40 'Delhi' 30 'F']
 ['H' 20 'Uttar Pradesh' 72 'M']
 ['I' 30 'Telangana' 22 'F']
 ['J' 18 'Chattisgarh' 42 'M']]
[ 0  3  1  4  5  6  2 10  0  7]


In [8]:
#Q8: Mention all your finding from the above given heatmap.
#Finding 1 - Income per month and Number of siblings are negatively correlated. As income per month increases, the number of siblings decreases
#Finding 2 - Age and Number of siblings are positively highly correlated. People who are older have more silings than younger ones.